=== rajatrathi/JavaTraining/Assessment2/src/main/resources/xsd/Flight.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.imcs/Flight"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.imcs/Flight" xmlns:pref="http://www.imcs/FlightDetails/FlightDetails" xmlns:pref1="http://www.imcs/FlightDetails">

	<import schemaLocation="FlightDetails.xsd" namespace="http://www.imcs/FlightDetails"></import>
	<complexType name="Flight">
		<sequence>
			<element name="flight_id" type="int"></element>
			<element name="airline_id" type="int"></element>
			<element name="airline_name" type="string"></element>
			<element name="from_location" type="string"></element>
			<element name="to_location" type="string"></element>
			<element name="departure_time" type="dateTime"></element>
			<element name="arrival_time" type="dateTime"></element>
			<element name="duration" type="int"></element>
			<element name="total_seats" type="int"></element>


			<element name="FlightDetails" type="pref:FlightDetails"></element>
		</sequence>
	</complexType>

	<element name="Flight" type="tns:Flight"></element>
</schema>

=== rajatrathi/JavaTraining/Assessment2/src/main/resources/xml/Flight.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Flight xmlns:tns="http://www.imcs/Flight" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.imcs/Flight ../xsd/Flight.xsd ">
  <tns:flight_id>0</tns:flight_id>
  <tns:airline_id>0</tns:airline_id>
  <tns:airline_name>tns:airline_name</tns:airline_name>
  <tns:from_location>tns:from_location</tns:from_location>
  <tns:to_location>tns:to_location</tns:to_location>
  <tns:departure_time>2001-12-31T12:00:00</tns:departure_time>
  <tns:arrival_time>2001-12-31T12:00:00</tns:arrival_time>
  <tns:duration>0</tns:duration>
  <tns:total_seats>0</tns:total_seats>
  <tns:FlightDetails>tns:FlightDetails</tns:FlightDetails>
</tns:Flight>
